import { SiAbletonlive, SiAdobephotoshop, SiAndroid, SiApple, SiAudi, SiBluetooth, SiCplusplus, SiDart, SiElixir, SiExpress, SiFacebook, SiFlutter, SiFord, SiGithub, SiGoogle, SiHaskell, SiHtml5, SiKotlin, SiLaravel, SiLine, SiMariadb, SiMercedes, SiMongodb, SiMysql, SiNestjs, SiNodedotjs, SiOpera, SiPhp, SiPostgresql, SiPython, SiReact, SiRedis, SiRubyonrails, SiRust, SiSafari, SiSamsung, SiSlack, SiSnapchat, SiSocketdotio, SiSurrealdb, SiSuzuki, SiSwift, SiThunderbird, SiTiktok, SiToyota, SiTypescript, SiUnity, SiVuedotjs } from 'react-icons/si'

export const DEV_ICONS = [
  SiElixir,
  SiNodedotjs,
  SiReact,
  SiRust,
  SiRubyonrails,
  SiPostgresql,
  SiMysql,
  SiHtml5,
  SiTypescript,
  SiExpress,
  SiCplusplus,
  SiLaravel,
  SiFlutter,
  SiDart,
  SiSocketdotio,
  SiRedis,
  SiSurrealdb,
  SiGithub,
  SiSwift,
  SiMongodb,
  SiNestjs,
  SiPhp,
  SiUnity,
  SiMariadb,
  SiAndroid,
  SiPython,
  SiKotlin,
  SiHaskell,
  SiVuedotjs
]

export const EXTRA_ICONS = [
  SiThunderbird,
  SiAbletonlive,
  SiBluetooth,
  SiAudi,
  SiSuzuki,
  SiToyota,
  SiFacebook,
  SiAdobephotoshop,
  SiFord,
  SiLine,
  SiSamsung,
  SiApple,
  SiOpera,
  SiSlack,
  SiGoogle,
  SiTiktok,
  SiMercedes,
  SiSnapchat,
  SiSafari
]
